#!/usr/bin/env node
/**
 * Agent graph — who hands work to whom, and how it went.
 *
 * Declared graph: config/agent-graph.json (generated by `build` from the hire
 * sheets' reportsTo, the project job moves, and the standing routes; an
 * `extra` block survives rebuilds). Undeclared handoffs are logged and warned
 * about, never blocked.
 *
 * Edge log: every handoff (passoff, consult, job stage, ticket, inbox ask,
 * sub session) is one edge on the Hub (POST /api/gotchibot/graph/edges). Each
 * edge is appended to sessions/graph/outbox.jsonl first and drained to the Hub,
 * so a Hub outage loses nothing.
 *
 * Watch (kanban-manager): an edge open past its kind's time budget, or closed
 * failed/dropped/rework, fires once — a Handoffs card on the project board and
 * a bot-inbox alert to the project manager (orchestrator if no PM is seated).
 *
 *   gotchibot graph [--days N] [--json]   report: flows, stalled, rework, off-graph
 *   gotchibot graph build                 regenerate config/agent-graph.json
 *   gotchibot graph sync                  drain the outbox to the Hub
 *   gotchibot graph watch [--json]        fire alerts for stalled / failed handoffs
 *   gotchibot graph plugin install        link the OpenClaw gateway plugin (bot runs + tokens)
 *   gotchibot graph plugin status         is it loaded, which hooks
 *
 * Gateway plugin (openclaw-plugins/gotchibot-graph → scripts/oc-graph-hooks.mjs):
 * one `run` edge per bot run with its tokens, and `spawn` edges for native
 * sub-agents. Runs are work, not handoffs: they feed the TOKENS section and
 * fire only on a token overrun.
 */
import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync, renameSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";
import { homedir } from "node:os";
import { isMainModule } from "./is-main.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const GRAPH_KINDS = ["passoff", "consult", "job", "ticket", "inbox", "spawn", "run"];
/**
 * Budgets per kind: an open edge past `minutes` is stalled; an edge whose
 * tokens.total passes `tokens` fires too. Tokens come from the gotchibot-graph
 * OpenClaw plugin (run and spawn edges); script-only kinds carry none yet.
 */
export const DEFAULT_BUDGETS = {
  consult: { minutes: 10, tokens: null },
  passoff: { minutes: 120, tokens: null },
  ticket: { minutes: 1440, tokens: null },
  job: { minutes: 1440, tokens: null },
  inbox: { minutes: 240, tokens: null },
  spawn: { minutes: 30, tokens: 1_000_000 },
  run: { minutes: 30, tokens: 400_000 },
};
/** Kinds that are work a bot did, not a handoff between two bots. */
const WORK_KINDS = new Set(["run"]);
const FAILED_OUTCOMES = new Set(["failed", "dropped", "rework"]);

function readJson(path, fallback) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return fallback;
  }
}

function graphPath(root = ROOT) {
  return join(root, "config", "agent-graph.json");
}
function outboxPath(root = ROOT) {
  return join(root, "sessions", "graph", "outbox.jsonl");
}

function testProcess() {
  return process.execArgv.includes("--test") || process.env.NODE_TEST_CONTEXT != null;
}

// ── roles ─────────────────────────────────────────────────────────────────

/** Orchestrator hero id from onboarding (no heavy imports — inbox/tickets import us). */
function orchHeroId(root = ROOT) {
  const ob = readJson(join(root, "sessions", ".onboarding.json"), {}) || {};
  return ob.orchestratorHeroId || null;
}

/** Role of a hero id ("userdefault", "orchestrator", or config/agent-roles.json). */
export function roleOf(id, { root = ROOT, roles } = {}) {
  const s = String(id || "").trim();
  if (!s) return null;
  if (/^(userdefault|user)$/i.test(s)) return "userdefault";
  if (/^(orch|orchestrator|gotchi)$/i.test(s) || s === orchHeroId(root)) return "orchestrator";
  const map = roles || readJson(join(root, "config", "agent-roles.json"), {}) || {};
  if (map[s]) return map[s];
  // Already a role name (e.g. consult --to project-manager)?
  const playbooks = readJson(join(root, "config", "agent-role-playbooks.json"), {}) || {};
  return playbooks[s] ? s : null;
}

// ── declared graph ────────────────────────────────────────────────────────

/** Edges every desk may use regardless of role (standing routes). */
function standingEdges() {
  const all = ["passoff", "consult", "inbox"];
  return [
    { from: "*", to: "orchestrator", kinds: all, why: "everyone reports up to orch" },
    { from: "orchestrator", to: "*", kinds: [...all, "spawn"], why: "orch delegates" },
    { from: "*", to: "chief-of-staff", kinds: ["consult", "inbox"], why: "escalation" },
    { from: "*", to: "kanban-manager", kinds: ["inbox", "ticket"], why: "PKM record rule" },
    { from: "project-manager", to: "kanban-manager", kinds: all, why: "PM ↔ kanban" },
    { from: "kanban-manager", to: "project-manager", kinds: all, why: "kanban alerts PM" },
    { from: "project-manager", to: "*", kinds: ["ticket", "passoff", "consult"], why: "PM staffs work" },
    { from: "*", to: "userdefault", kinds: ["inbox"], why: "notify UserDefault" },
    { from: "userdefault", to: "*", kinds: all, why: "UserDefault can ask anyone" },
  ];
}

/** Build the declared graph from hire sheets + job moves + standing routes. */
export async function buildGraph({ root = ROOT } = {}) {
  const { hireFor } = await import("./hire-sheet.mjs");
  const { JOB_MOVES, STAGE_OWNER } = await import("./project-tickets.mjs");
  const playbooks = readJson(join(root, "config", "agent-role-playbooks.json"), {}) || {};
  const prev = readJson(graphPath(root), {}) || {};
  const edges = [];
  const add = (from, to, kinds, why) => {
    if (!from || !to || from === to) return;
    const hit = edges.find((e) => e.from === from && e.to === to);
    if (hit) {
      hit.kinds = [...new Set([...hit.kinds, ...kinds])];
      return;
    }
    edges.push({ from, to, kinds: [...kinds], why });
  };
  for (const [role, pb] of Object.entries(playbooks)) {
    const h = hireFor(role, pb);
    if (role !== "orchestrator") add(role, h.reportsTo || "orchestrator", ["inbox", "consult", "passoff"], "reportsTo");
  }
  for (const key of Object.keys(JOB_MOVES)) {
    const [a, b] = key.split("→");
    add(STAGE_OWNER[a], STAGE_OWNER[b], ["job"], `job ${key}`);
  }
  for (const e of standingEdges()) add(e.from, e.to, e.kinds, e.why);
  const graph = {
    $comment: "Generated by `gotchibot graph build` (hire sheets, project job moves, standing routes). Put hand-made edges in `extra`; they survive rebuilds.",
    version: 1,
    builtAt: new Date().toISOString(),
    budgets: { ...DEFAULT_BUDGETS, ...(prev.budgets || {}) },
    edges,
    extra: Array.isArray(prev.extra) ? prev.extra : [],
  };
  mkdirSync(dirname(graphPath(root)), { recursive: true });
  writeFileSync(graphPath(root), `${JSON.stringify(graph, null, 2)}\n`);
  return graph;
}

export function loadGraph({ root = ROOT } = {}) {
  const g = readJson(graphPath(root), null);
  if (g) return g;
  return { budgets: DEFAULT_BUDGETS, edges: standingEdges(), extra: [] };
}

/** Is fromRole → toRole allowed for this kind? Unknown roles count as undeclared. */
export function isDeclared(fromRole, toRole, kind, graph = loadGraph()) {
  if (!fromRole || !toRole) return false;
  const all = [...(graph.edges || []), ...(graph.extra || [])];
  return all.some(
    (e) =>
      (e.from === fromRole || e.from === "*") &&
      (e.to === toRole || e.to === "*") &&
      (!e.kinds || e.kinds.includes(kind)),
  );
}

// ── edge log (outbox → Hub) ───────────────────────────────────────────────

export function newEdgeId(kind, ref) {
  const r = String(ref || "").replace(/[^A-Za-z0-9_.:-]+/g, "-").slice(0, 60);
  return `${kind}:${r || randomBytes(4).toString("hex")}`;
}

/**
 * Record (or update) one edge. Fills roles + `declared`, warns once on stderr
 * for an undeclared edge, appends to the outbox, then tries to drain it to the
 * Hub. Never throws into the caller; returns the edge as recorded.
 */
export async function recordEdge(edge, { root, hubRequest, graph, warn = true, flush = true } = {}) {
  // Under `node --test`, only record when a test hands us its own root or Hub
  // client — other tests run the inbox/ticket/passoff code, and their edges
  // must not land in the real outbox (and from there on the Hub).
  if (testProcess() && !root && !hubRequest) return null;
  root = root || ROOT;
  try {
    const e = { ...edge };
    if (!e.edgeId) e.edgeId = newEdgeId(e.kind || "edge", e.ref);
    const opening = Boolean(e.from && e.to && e.kind);
    if (opening) {
      e.fromRole = e.fromRole || roleOf(e.from, { root });
      e.toRole = e.toRole || roleOf(e.to, { root });
      e.sentAt = e.sentAt || new Date().toISOString();
      if (typeof e.declared !== "boolean") e.declared = isDeclared(e.fromRole, e.toRole, e.kind, graph || loadGraph({ root }));
      if (!e.declared && warn) {
        process.stderr.write(`graph: ${e.fromRole || e.from} → ${e.toRole || e.to} (${e.kind}) is not a declared edge — logged\n`);
      }
    }
    for (const k of Object.keys(e)) if (e[k] == null) delete e[k];
    mkdirSync(dirname(outboxPath(root)), { recursive: true });
    appendFileSync(outboxPath(root), `${JSON.stringify(e)}\n`);
    if (flush) await flushOutbox({ root, hubRequest }).catch(() => {});
    return e;
  } catch {
    return null;
  }
}

/** Close an edge: answeredAt now, with an outcome. */
export function closeEdge(edgeId, outcome = "answered", opts = {}) {
  return recordEdge({ edgeId, answeredAt: opts.at || new Date().toISOString(), outcome }, opts);
}

export function readOutbox(root = ROOT) {
  try {
    return readFileSync(outboxPath(root), "utf8")
      .split("\n")
      .filter(Boolean)
      .map((l) => {
        try {
          return JSON.parse(l);
        } catch {
          return null;
        }
      })
      .filter(Boolean);
  } catch {
    return [];
  }
}

/** Drain the outbox to the Hub in batches; keep whatever did not land. */
export async function flushOutbox({ root = ROOT, hubRequest } = {}) {
  const rows = readOutbox(root);
  if (!rows.length) return { sent: 0, left: 0 };
  if (!hubRequest && testProcess()) return { sent: 0, left: rows.length, skipped: "test" };
  if (!existsSync(join(root, "sessions", ".hub.json")) && !hubRequest) return { sent: 0, left: rows.length, skipped: "unpaired" };
  const request = hubRequest || (await import("./chat-hub-client.mjs")).hubRequest;
  let sent = 0;
  for (let i = 0; i < rows.length; i += 200) {
    const batch = rows.slice(i, i + 200);
    try {
      await request("POST", "/api/gotchibot/graph/edges", { body: { edges: batch }, signal: AbortSignal.timeout(8000) });
      sent += batch.length;
    } catch {
      break;
    }
  }
  const left = rows.slice(sent);
  const tmp = `${outboxPath(root)}.tmp`;
  writeFileSync(tmp, left.map((r) => JSON.stringify(r)).join("\n") + (left.length ? "\n" : ""));
  renameSync(tmp, outboxPath(root));
  return { sent, left: left.length };
}

/** Merge edge records by edgeId (later fields win) — Hub list + local outbox. */
export function mergeEdges(...lists) {
  const byId = new Map();
  for (const list of lists) {
    for (const e of list || []) {
      if (!e?.edgeId) continue;
      byId.set(e.edgeId, { ...(byId.get(e.edgeId) || {}), ...e });
    }
  }
  return [...byId.values()];
}

/** All edges this desk can see: the Hub's (if reachable) plus anything still queued. */
export async function loadEdges({ root = ROOT, hubRequest, days = 7 } = {}) {
  let hub = [];
  let hubOk = false;
  if (hubRequest || (!testProcess() && existsSync(join(root, "sessions", ".hub.json")))) {
    try {
      const request = hubRequest || (await import("./chat-hub-client.mjs")).hubRequest;
      const since = new Date(Date.now() - days * 86400_000).toISOString();
      const r = await request("GET", "/api/gotchibot/graph/edges", { query: { since }, signal: AbortSignal.timeout(8000) });
      hub = Array.isArray(r?.edges) ? r.edges : [];
      hubOk = true;
    } catch {
      /* offline: outbox only */
    }
  }
  return { edges: mergeEdges(hub, readOutbox(root)), hubOk };
}

// ── report ────────────────────────────────────────────────────────────────

function pct(sorted, p) {
  if (!sorted.length) return null;
  return sorted[Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length))];
}

function budgetFor(kind, graph) {
  return (graph?.budgets || DEFAULT_BUDGETS)[kind] || DEFAULT_BUDGETS[kind] || {};
}
function budgetMs(kind, graph) {
  return (budgetFor(kind, graph).minutes ?? 60) * 60_000;
}

/** Why an edge fires (stalled / failed), or null. */
export function fireReason(e, { now = Date.now(), graph = loadGraph() } = {}) {
  // A failed bot run is a model/tool error the bot already saw; only its token
  // overrun is a kanban → PM matter. Failed handoffs and sub-agents fire.
  if (e.outcome && FAILED_OUTCOMES.has(e.outcome) && !WORK_KINDS.has(e.kind)) return `${e.outcome}`;
  const tokenBudget = budgetFor(e.kind, graph).tokens;
  if (tokenBudget && Number(e.tokens?.total) > tokenBudget) return `used ${fmtTokens(e.tokens.total)} tokens (budget ${fmtTokens(tokenBudget)})`;
  if (!e.answeredAt && e.sentAt) {
    const age = now - Date.parse(e.sentAt);
    if (age > budgetMs(e.kind, graph)) return `open ${Math.round(age / 60000)}m (budget ${Math.round(budgetMs(e.kind, graph) / 60000)}m)`;
  }
  return null;
}

export function fmtTokens(n) {
  n = Number(n) || 0;
  if (n >= 1e6) return `${(n / 1e6).toFixed(1)}M`;
  if (n >= 1e3) return `${Math.round(n / 1e3)}k`;
  return String(n);
}

/** Tokens per bot (run edges): runs, failed, total, median per run, top model. */
export function tokenReport(edges) {
  const byBot = new Map();
  for (const e of edges) {
    if (e.kind !== "run") continue;
    const key = e.toRole || e.to || "?";
    const b = byBot.get(key) || { bot: key, runs: 0, failed: 0, total: 0, per: [], models: new Map() };
    b.runs++;
    if (e.outcome === "failed") b.failed++;
    const t = Number(e.tokens?.total) || 0;
    b.total += t;
    if (t) b.per.push(t);
    if (e.model) b.models.set(e.model, (b.models.get(e.model) || 0) + 1);
    byBot.set(key, b);
  }
  return [...byBot.values()]
    .map((b) => {
      const s = b.per.sort((x, y) => x - y);
      const model = [...b.models.entries()].sort((x, y) => y[1] - x[1])[0]?.[0] || null;
      return { bot: b.bot, runs: b.runs, failed: b.failed, tokens: b.total, medianTokens: s.length ? pct(s, 50) : null, model };
    })
    .sort((a, b) => b.tokens - a.tokens);
}

export function graphReport(edges, { now = Date.now(), graph = loadGraph() } = {}) {
  const pairs = new Map();
  for (const e of edges) {
    if (!e.kind || WORK_KINDS.has(e.kind)) continue;
    const key = `${e.fromRole || e.from || "?"} → ${e.toRole || e.to || "?"}`;
    const p = pairs.get(key) || { pair: key, count: 0, open: 0, failed: 0, ms: [] };
    p.count++;
    if (!e.answeredAt) p.open++;
    if (e.outcome && FAILED_OUTCOMES.has(e.outcome)) p.failed++;
    if (e.sentAt && e.answeredAt) p.ms.push(Date.parse(e.answeredAt) - Date.parse(e.sentAt));
    pairs.set(key, p);
  }
  const flows = [...pairs.values()]
    .map((p) => {
      const s = p.ms.sort((a, b) => a - b);
      return { pair: p.pair, count: p.count, open: p.open, failed: p.failed, medianMin: s.length ? Math.round(pct(s, 50) / 60000) : null, p90Min: s.length ? Math.round(pct(s, 90) / 60000) : null };
    })
    .sort((a, b) => b.count - a.count);
  const stalled = edges.filter((e) => !e.answeredAt && fireReason(e, { now, graph })).map((e) => ({ ...e, reason: fireReason(e, { now, graph }) }));
  const overBudget = edges
    .filter((e) => e.answeredAt && !FAILED_OUTCOMES.has(e.outcome) && /tokens/.test(fireReason(e, { now, graph }) || ""))
    .map((e) => ({ ...e, reason: fireReason(e, { now, graph }) }));
  const reworkByRef = new Map();
  for (const e of edges) if (e.kind === "ticket" && e.outcome === "rework") reworkByRef.set(e.ref, (reworkByRef.get(e.ref) || 0) + 1);
  const rework = [...reworkByRef.entries()].filter(([, n]) => n >= 2).map(([ref, n]) => ({ ref, reworks: n }));
  const offGraph = edges.filter((e) => e.declared === false && !WORK_KINDS.has(e.kind));
  const open = edges
    .filter((e) => e.kind && !e.answeredAt && !WORK_KINDS.has(e.kind))
    .sort((a, b) => String(a.sentAt).localeCompare(String(b.sentAt)))
    .slice(0, 60)
    .map((e) => ({ ...e, stalled: Boolean(fireReason(e, { now, graph })), reason: fireReason(e, { now, graph }) }));
  const handoffs = edges.filter((e) => e.kind && !WORK_KINDS.has(e.kind)).length;
  return { flows, stalled, rework, offGraph, open, tokens: tokenReport(edges), overBudget, total: handoffs, runs: edges.length - handoffs };
}

function fmtReport(r, { hubOk }) {
  const out = [`agent graph — ${r.total} handoff(s)${r.runs ? ` · ${r.runs} bot run(s)` : ""}${hubOk ? "" : " · Hub unreachable: local outbox only"}`, ""];
  out.push("FLOWS (count · open · failed · median / p90 min to answer)");
  for (const f of r.flows.slice(0, 20)) out.push(`  ${f.pair.padEnd(42)} ${String(f.count).padStart(3)} · ${f.open} open · ${f.failed} failed · ${f.medianMin ?? "—"} / ${f.p90Min ?? "—"}`);
  if (!r.flows.length) out.push("  (none yet)");
  out.push("", "STALLED");
  for (const e of r.stalled.slice(0, 15)) out.push(`  ${e.kind.padEnd(8)} ${(e.fromRole || e.from)} → ${(e.toRole || e.to)}  ${e.reason}  ${e.title || e.ref || e.edgeId}`);
  if (!r.stalled.length) out.push("  (none)");
  out.push("", "REWORK LOOPS (ticket bounced ≥2×)");
  for (const x of r.rework) out.push(`  ${x.ref}  ${x.reworks}×`);
  if (!r.rework.length) out.push("  (none)");
  out.push("", "TOKENS by bot (gateway runs · failed · total · median per run · model)");
  for (const t of (r.tokens || []).slice(0, 15)) out.push(`  ${t.bot.padEnd(22)} ${String(t.runs).padStart(4)} runs · ${t.failed} failed · ${fmtTokens(t.tokens).padStart(6)} · ${t.medianTokens == null ? "—" : fmtTokens(t.medianTokens)}  ${t.model || ""}`);
  if (!r.tokens?.length) out.push("  (none — install the gateway plugin: gotchibot graph plugin install)");
  for (const e of (r.overBudget || []).slice(0, 10)) out.push(`  ! ${e.kind} ${e.fromRole || e.from} → ${e.toRole || e.to}  ${e.reason}`);
  out.push("", "OFF-GRAPH (not in config/agent-graph.json)");
  for (const e of r.offGraph.slice(0, 15)) out.push(`  ${e.kind} ${(e.fromRole || e.from)} → ${(e.toRole || e.to)}  ${e.title || e.ref || ""}`);
  if (!r.offGraph.length) out.push("  (none)");
  return out.join("\n");
}

// ── watch (kanban-manager → PM) ───────────────────────────────────────────

/**
 * Fire each stalled/failed edge once: mark it alerted on the Hub, put a card
 * on the project board's Handoffs lane, and alert the project manager.
 */
export async function watchEdges({ root = ROOT, hubRequest, now = Date.now(), send, addHandoffCard, edges, mark } = {}) {
  const graph = loadGraph({ root });
  const list = edges || (await loadEdges({ root, hubRequest })).edges;
  const fired = [];
  for (const e of list) {
    if (e.alertedAt) continue;
    const reason = fireReason(e, { now, graph });
    if (!reason) continue;
    fired.push({ ...e, reason });
  }
  if (!fired.length) return { fired: [] };
  const inbox = send || (await import("./bot-inbox.mjs")).sendMessage;
  const card = addHandoffCard || defaultHandoffCard;
  const results = [];
  for (const e of fired) {
    const who = `${e.fromRole || e.from} → ${e.toRole || e.to}`;
    const body = [
      `Handoff ${e.kind} ${who} needs a decision: ${e.reason}.`,
      `Ref: ${e.ref || e.edgeId}${e.title ? ` — ${e.title}` : ""}`,
      "Act: nudge the owner, re-route to another seated desk (passoff/consult), or escalate to chief-of-staff. Record it with pkm-record.",
    ].join("\n");
    let to = "project-manager";
    let delivered = false;
    for (const target of ["project-manager", "orch"]) {
      try {
        inbox({ to: target, from: "kanban-manager", kind: "alert", subject: `Handoff ${e.reason}: ${who}`, body, project: e.project || null });
        to = target;
        delivered = true;
        break;
      } catch {
        /* no PM seated → orch */
      }
    }
    let cardId = null;
    try {
      cardId = await card(e, { root });
    } catch {
      /* no project selected */
    }
    const at = new Date(now).toISOString();
    // On the Hub the runner writes the store directly; desks go through the edge log.
    if (mark) await mark(e, e.reason, at);
    else await recordEdge({ edgeId: e.edgeId, alertedAt: at, alertReason: e.reason }, { root, hubRequest });
    results.push({ edgeId: e.edgeId, reason: e.reason, alerted: delivered ? to : null, cardId });
  }
  return { fired: results };
}

/** Handoffs lane on the selected project's main board (review column, linked by edgeId). */
async function defaultHandoffCard(e) {
  const k = await import("./project-kanban.mjs");
  const board = k.ensureMainBoard();
  if (board.cards.some((c) => c.edgeId === e.edgeId)) return null;
  const c = k.addCard(board, { title: `Handoff: ${e.fromRole || e.from} → ${e.toRole || e.to} · ${e.reason}`, column: "review", owner: "project-manager", source: "handoff" });
  c.edgeId = e.edgeId;
  k.saveBoard(k.mainKanbanPath(), board);
  return c.id;
}

// ── CLI ───────────────────────────────────────────────────────────────────

// ── gateway plugin (bot runs, tokens, native sub-agents) ─────────────────

export const GRAPH_PLUGIN_ID = "gotchibot-graph";

function openclawBin() {
  const local = join(homedir(), ".openclaw", "bin", "openclaw");
  return existsSync(local) ? local : "openclaw";
}

function oc(args, { quiet = false } = {}) {
  const r = spawnSync(openclawBin(), args, { encoding: "utf8", timeout: 120_000 });
  if (!quiet && r.status !== 0) process.stderr.write(r.stderr || r.stdout || "");
  return { ok: r.status === 0, out: (r.stdout || "").trim(), err: (r.stderr || "").trim(), missing: r.error?.code === "ENOENT" };
}

/** JSON from an openclaw command that may print a banner line first. */
function ocJson(text) {
  const i = text.search(/[[{]/);
  if (i < 0) return null;
  try {
    return JSON.parse(text.slice(i));
  } catch {
    return null;
  }
}

/**
 * Install (link) the gotchibot-graph plugin into this machine's OpenClaw and
 * allow it the conversation hooks (llm_output, agent_end) it needs for tokens.
 */
export function installGraphPlugin({ root = ROOT, run = oc } = {}) {
  const dir = join(root, "openclaw-plugins", GRAPH_PLUGIN_ID);
  const steps = [];
  // --force: OpenClaw cancels any local-path install without it (outside ClawHub
  // review). The source is this repo, and this runs only from the explicit
  // `gotchibot graph plugin install` an operator types.
  const inst = run(["plugins", "install", "--link", "--force", dir], { quiet: true });
  if (inst.missing) return { ok: false, steps, error: "openclaw is not installed on this machine" };
  const already = /already|exists/i.test(`${inst.err} ${inst.out}`);
  steps.push({ step: "link", ok: inst.ok || already, note: inst.ok ? "linked" : already ? "already linked" : inst.err.split("\n").pop() });
  if (!inst.ok && !already) return { ok: false, steps, error: `plugins install failed: ${inst.err || inst.out}` };
  const allow = ocJson(run(["config", "get", "plugins.allow", "--json"], { quiet: true }).out);
  if (Array.isArray(allow) && !allow.includes(GRAPH_PLUGIN_ID)) {
    const r = run(["config", "set", "plugins.allow", JSON.stringify([...allow, GRAPH_PLUGIN_ID]), "--strict-json"]);
    steps.push({ step: "allow", ok: r.ok });
  } else steps.push({ step: "allow", ok: true, note: Array.isArray(allow) ? "already allowed" : "no allowlist" });
  for (const [path, note] of [
    [`plugins.entries.${GRAPH_PLUGIN_ID}.enabled`, "enabled"],
    [`plugins.entries.${GRAPH_PLUGIN_ID}.hooks.allowConversationAccess`, "token hooks allowed"],
  ]) {
    const r = run(["config", "set", path, "true", "--strict-json"]);
    steps.push({ step: note, ok: r.ok });
  }
  return { ok: steps.every((s) => s.ok), steps };
}

/** Is the plugin loaded with its hooks? (module-loaded inspection, no gateway needed) */
export function graphPluginStatus({ run = oc } = {}) {
  const r = run(["plugins", "inspect", GRAPH_PLUGIN_ID, "--runtime", "--json"], { quiet: true });
  if (r.missing) return { installed: false, error: "openclaw is not installed on this machine" };
  if (!r.ok) return { installed: false, error: (r.err || r.out).split("\n").find((l) => l.trim()) || "inspect failed" };
  const j = ocJson(r.out) || {};
  const text = JSON.stringify(j);
  const hooks = ["llm_output", "agent_end", "subagent_spawned", "subagent_ended"].filter((h) => text.includes(h));
  return { installed: true, hooks, raw: j };
}

async function main(argv) {
  const cmd = argv[0] && !argv[0].startsWith("-") ? argv[0] : "report";
  const json = argv.includes("--json");
  const di = argv.indexOf("--days");
  const days = di >= 0 ? Number(argv[di + 1]) || 7 : 7;
  if (cmd === "build") {
    const g = await buildGraph();
    console.log(`config/agent-graph.json — ${g.edges.length} edges (+${g.extra.length} extra)`);
    return 0;
  }
  if (cmd === "sync") {
    const r = await flushOutbox();
    console.log(json ? JSON.stringify(r) : `sent ${r.sent} · queued ${r.left}${r.skipped ? ` (${r.skipped})` : ""}`);
    return 0;
  }
  if (cmd === "watch") {
    await flushOutbox().catch(() => {});
    const r = await watchEdges();
    console.log(json ? JSON.stringify(r, null, 2) : r.fired.length ? r.fired.map((f) => `fired ${f.edgeId}  ${f.reason}  → ${f.alerted || "(no alert target)"}`).join("\n") : "no stalled or failed handoffs");
    return 0;
  }
  if (cmd === "plugin") {
    const sub = argv[1] || "status";
    if (sub === "install") {
      const r = installGraphPlugin();
      if (json) console.log(JSON.stringify(r, null, 2));
      else {
        for (const s of r.steps) console.log(`${s.ok ? "✓" : "✗"} ${s.step}${s.note ? ` — ${s.note}` : ""}`);
        console.log(r.ok ? "Restart the OpenClaw gateway to load it (Hub: systemctl --user restart openclaw-gateway)." : r.error || "install incomplete");
      }
      return r.ok ? 0 : 1;
    }
    if (sub === "status") {
      const r = graphPluginStatus();
      if (json) console.log(JSON.stringify(r, null, 2));
      else console.log(r.installed ? `${GRAPH_PLUGIN_ID}: installed · hooks ${r.hooks.join(", ") || "(none registered — check plugins.entries.${GRAPH_PLUGIN_ID}.hooks.allowConversationAccess)"}` : `${GRAPH_PLUGIN_ID}: not installed (${r.error}) — gotchibot graph plugin install`);
      return r.installed ? 0 : 1;
    }
    console.error("usage: gotchibot graph plugin [status|install] [--json]");
    return 2;
  }
  if (cmd === "report") {
    await flushOutbox().catch(() => {});
    const { edges, hubOk } = await loadEdges({ days });
    const r = graphReport(edges);
    console.log(json ? JSON.stringify({ hubOk, ...r }, null, 2) : fmtReport(r, { hubOk }));
    return 0;
  }
  console.error("usage: gotchibot graph [report] [--days N] [--json] | build | sync | watch [--json] | plugin [status|install]");
  return 2;
}

if (isMainModule(import.meta.url)) {
  main(process.argv.slice(2)).then((c) => process.exit(c ?? 0), (e) => {
    console.error(e?.message || e);
    process.exit(1);
  });
}
