#!/usr/bin/env bash
set -euo pipefail

DEV_ROOT="${GOTCHIBOT_DEV_ROOT:-$HOME/Dev}"
OUT_NAME="KNOWLEDGE.md"

if [ $# -gt 0 ]; then
  dirs=("$@")
else
  dirs=()
  for d in "$DEV_ROOT"/*/; do
    [ -d "$d/.git" ] && dirs+=("${d%/}")
  done
fi

for proj in "${dirs[@]}"; do
  [ -d "$proj" ] || continue
  out="$proj/$OUT_NAME"
  tmp="$proj/.KNOWLEDGE.tmp.$$"

  {
    echo "# $OUT_NAME — $(basename "$proj")"
    echo
    echo "Auto-generated by scripts/unify-md.sh — do not edit; regenerate instead."
    echo "Generated: $(date '+%Y-%m-%d %H:%M')"
    echo
  } > "$tmp"

  seen_titles=""

  while IFS= read -r -d '' f; do
    rel="${f#"$proj"/}"
    title="$(basename "$f" .md)"
    case ",$seen_titles," in *",$title,"*) title="";; esac
    [ -n "$title" ] && seen_titles="$seen_titles,$title"

    {
      echo "## $rel"
      grep -E '^#{1,2} ' "$f" | head -20 | sed 's/^###*/•/'
      echo
    } >> "$tmp"
  done < <(
    find "$proj" -maxdepth 2 \( \
      -path '*/node_modules' -o -path '*/.git' -o -path '*/sessions' -o \
      -name "$OUT_NAME" -o -name '.DS_Store' \) -prune -o \
      -type f -name '*.md' -print0 2>/dev/null | sort -z
  )

  mv "$tmp" "$out"
  echo "$(basename "$proj"): $out ($(grep -c '^## ' "$out") sources)"
done
